Repository TheFatPanda97/Isomo, pull requests merged in 2020-05, with the labels that each got.

#10 novice me test
  .vuepress/components/Hello.vue
Labels: good first issue

#12 User journey
  .vuepress/config.js
  Applicant/README.md
  Recruiter/README.md
  Research/README.md
  tab3/README.md
  tab4/README.md
Labels: documentation

#20 Home screen
  packages/app/package-lock.json
  packages/app/package.json
  packages/app/public/index.html
  packages/app/src/App.vue
  packages/app/src/assets/homebackground.jpg
  packages/app/src/assets/logo.png
  packages/app/src/components/AppBar.vue
  packages/app/src/components/AppBarBtn.vue
  packages/app/src/components/HelloWorld.vue
  packages/app/src/main.js
  packages/app/src/plugins/vuetify.js
  packages/app/src/router/index.js
  packages/app/src/views/HomePage.vue
  packages/app/vue.config.js
Labels: enhancement
